### ISSUE TITLE
more unit tests!

### ISSUE THREAD

**Issue by nbokulich** [caporaso-lab/tax-credit#124]
We need unit tests for:
`mock_quality.py`
`eval_framework._multiple_match_kludge`

Hope you don't mind me assigning you @BenKaehler — I could help with some of `mock_quality` if needed, but you'll know your code best.

`eval_framework._multiple_match_kludge` also *BREAKS* the pre-existing eval_framework unit tests (which I think I calculated by hand so should be correct). My gut instinct is that the kludge is causing `exp` and `obs` to be returned in the wrong order, leading to the wrong weights being applied during precision/recall calculation. The specific error I get is:
```
======================================================================
FAIL: p, r, and f on individual expected sequences, excluding specific
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nbokulich/Desktop/projects/short-read-tax-assignment/tax_credit/tests/test_eval_framework.py", line 201, in test_per_sequence_precision_exclude
    self.assertAlmostEqual(p, ep)
AssertionError: 0.91666666666666663 != 0.25 within 7 places
```

This indicates that we are getting the wrong precision score — very high precision when we expect very low precision. This is on an OTU table that looks like this:
```
OTU ID          s1    s2   s3	s4
o1             1.0   2.0  3.0  4.0
o2             2.0   0.0  7.0  8.0
o3             9.0   10.0 11.0 12.0
```
`exp` taxa look like this:
```
        _exp_taxa = '\n'.join(
            ['o1\tAa;Bb;Cc;Dd;Ee;Ff;Gg',
             'o2\tAa;Bb;Cc;Dd;Ee;Ff;Hh',
             'o3\tAa;Ii;Jj;Kk;Ll;Mm;Nn',
             'o4\tAa;Ii;Jj;Kk;Ll;Mm;Oo'])
```
and `obs` taxa look like this:
```
        _obs_taxa = '\n'.join(
            ['o1\tAa;Bb;Cc;Dd;Ee;Ff;Gg',
             'o2\tAa;Bb;Cc;Dd;Ee;Ff;Ii',
             'o3\tAa;Ii;Pp;Qq;Rr;Tt',
             'o4\tAa;Ii;Jj;Kk;Ll;Mm;Oo'])
```

The error is emerging on level 2 in observation `o3`, where we expect label `Jj` but observe `Pp`... `o3` is the most abundant organism in each sample by a wide margin, so should have a high weight, causing precision to crash even though the other two observations are correct. However, we observe very high precision, leading me to believe that the `obs` and `exp` label lists are being reshuffled incorrectly, and the label mismatches are probably instead being attributed to `o1`

**Comment by BenKaehler** [comment]
Fixed on #131
