### ISSUE TITLE
fungal precision/recall results are failing

### ISSUE THREAD

**Issue by nbokulich** [caporaso-lab/tax-credit#129]
thanks @BenKaehler for brining this up.

Fungal results are failing precision/recall tests suddenly. This seems to be occurring across all datasets/methods now (e.g., [here](https://github.com/BenKaehler/short-read-tax-assignment/blob/dev/ipynb/mock-community/evaluate-classification-accuracy-naive-bayes.ipynb)), which leads me to suspect that the expected taxonomies/sequences must have been altered (or not altered). 

May be related to #118

**Comment by nbokulich** [comment]
from @BenKaehler : 
>The problem is that those species get dropped when I extract the amplicons. The don't seem to match the primers at all

So this is occurring during the amplicon extraction.

use full ref dbs?

**Comment by nbokulich** [comment]
I suspect what may be happening is this:
the missing ref seqs should be in full UNITE, covering the primer region. After OTU clustering (99%), these seqs could be dropped — so even though the names are still present, seqs containing the primer region may be missing from the ref.

Need to check ref to confirm that the primers match the ref seqs for these taxa:
```k__Fungi;p__Chytridiomycota;c__Chytridiomycetes;o__Spizellomycetales;f__Spizellomycetaceae;g__Spizellomyces;s__Spizellomyces_punctatus
k__Fungi;p__Basidiomycota;c__Agaricomycetes;o__Cantharellales;f__Hydnaceae;g__Sistotrema;s__Sistotrema_brinkmannii
k__Fungi;p__Ascomycota;c__Saccharomycetes;o__Saccharomycetales;f__Saccharomycetales_fam_Incertae_sedis;g__Debaryomyces;s__Debaryomyces_prosopidis
k__Fungi;p__Basidiomycota;c__Agaricomycetes;o__Agaricales;f__Amanitaceae;g__Amanita;s__Amanita_lividopallescens
k__Fungi;p__Ascomycota;c__Leotiomycetes;o__Helotiales;f__Helotiaceae;g__Hymenoscyphus;s__Hymenoscyphus_fraxineus
k__Fungi;p__Ascomycota;c__Archaeorhizomycetes;o__Archaeorhizomycetales;f__Archaeorhizomycetaceae;g__Archaeorhizomyces;s__Archaeorhizomyces_finlayi
k__Fungi;p__Ascomycota;c__Sordariomycetes;o__Hypocreales;f__Nectriaceae;g__Fusarium;s__Fusarium_poae
k__Fungi;p__Ascomycota;c__Pezizomycetes;o__Pezizales;f__Rhizinaceae;g__Rhizina;s__Rhizina_undulata
k__Fungi;p__Basidiomycota;c__Agaricomycetes;o__Agaricales;f__Cortinariaceae;g__Cortinarius;s__Cortinarius_purpurascens
```

**Comment by BenKaehler** [comment]
More details!

The primers `AACTTTYRRCAAYGGATCWCT` and `AGCCTCCGCTTATTGATATGCTTAART` make this sequence disappear:
```
k__Fungi;p__Chytridiomycota;c__Chytridiomycetes;o__Spizellomycetales;f__Spizellomycetaceae;g__Spizellomyces;s__Spizellomyces_punctatus
```

The primers `CTTGGTCATTTAGAGGAAGTAA` and `TCCTCCGCTTATTGATATGC` make these sequences go missing:
```
k__Fungi;p__Basidiomycota;c__Agaricomycetes;o__Cantharellales;f__Hydnaceae;g__Sistotrema;s__Sistotrema_brinkmannii
k__Fungi;p__Ascomycota;c__Saccharomycetes;o__Saccharomycetales;f__Saccharomycetales_fam_Incertae_sedis;g__Debaryomyces;s__Debaryomyces_prosopidis
k__Fungi;p__Basidiomycota;c__Agaricomycetes;o__Agaricales;f__Amanitaceae;g__Amanita;s__Amanita_lividopallescens
k__Fungi;p__Ascomycota;c__Leotiomycetes;o__Helotiales;f__Helotiaceae;g__Hymenoscyphus;s__Hymenoscyphus_fraxineus
k__Fungi;p__Ascomycota;c__Archaeorhizomycetes;o__Archaeorhizomycetales;f__Archaeorhizomycetaceae;g__Archaeorhizomyces;s__Archaeorhizomyces_finlayi
k__Fungi;p__Ascomycota;c__Sordariomycetes;o__Hypocreales;f__Nectriaceae;g__Fusarium;s__Fusarium_poae
k__Fungi;p__Ascomycota;c__Pezizomycetes;o__Pezizales;f__Rhizinaceae;g__Rhizina;s__Rhizina_undulata
k__Fungi;p__Basidiomycota;c__Agaricomycetes;o__Agaricales;f__Cortinariaceae;g__Cortinarius;s__Cortinarius_purpurascens
```

The primers `GAACGCAGCRAANNGYGA` and `TCCTCCGCTTATTGATATGC` eliminate these sequences:
```
k__Fungi;p__Ascomycota;c__Leotiomycetes;o__Helotiales;f__Helotiaceae;g__Hymenoscyphus;s__Hymenoscyphus_fraxineus
k__Fungi;p__Ascomycota;c__Archaeorhizomycetes;o__Archaeorhizomycetales;f__Archaeorhizomycetaceae;g__Archaeorhizomyces;s__Archaeorhizomyces_finlayi
k__Fungi;p__Ascomycota;c__Sordariomycetes;o__Hypocreales;f__Nectriaceae;g__Fusarium;s__Fusarium_poae
k__Fungi;p__Basidiomycota;c__Agaricomycetes;o__Agaricales;f__Cortinariaceae;g__Cortinarius;s__Cortinarius_purpurascens
```

**Comment by nbokulich** [comment]
@BenKaehler . My investigation confirms my suspicions (see my previous comment). All of these species are present in the full UNITE db, and all of these primers hit the expected seqs for these species (which are, incidentally, ref seqs in the full UNITE db). Yet, the sequences in the 99% sequences are not the same as the expected sequences.

`AACTTTYRRCAAYGGATCWCT` hits all sequences.

`s__Spizellomyces_punctatus` hits `AACTTTYRRCAAYGGATCWCT` but just misses the reverse primer `AGCCTCCGCTTATTGATATGCTTAART`

`CTTGGTCATTTAGAGGAAGTAA` hits upstream (5') of the start site for many of these seqs, and `TCCTCCGCTTATTGATATGC` hits downstream (3'), hence the poor performance for that pair.

`GAACGCAGCRAANNGYGA` hits everything, but `TCCTCCGCTTATTGATATGC`hits downstream (3'), leading to several misses.

We have a few options here:

1. We use the full (untrimmed) references. Obviously this may still fail (or hinder) classification, since the sequences would be truncated. However, the "heart" of the sequences would remain, offering something potentially useful.

2. We augment the ref dbs with the expected-seqs from all fungal mock communities. For at least some of these mock communities, the expected seqs DO MATCH the primers (I hand checked them some time ago). Then proceed with trimming, etc. This has the disadvantage that we aren't using a "normal" ref db, but it serves the purpose of assessing accuracy.

3. We alter the eval to ignore any species that is not represented in the ref db after trimming. This complicates matters and could bias results, so I don't like it.

4. We drop these mock communities. Only use mock communities that have primer-matching seqs in the ref db — this probably puts us back with mock-9 and mock-10.

**Comment by BenKaehler** [comment]
I'm doing 1.

**Comment by nbokulich** [comment]
solved. thanks @BenKaehler !
