### ISSUE TITLE
Files not in the repository?

### ISSUE THREAD

**Issue by Leo-alves** [caporaso-lab/tax-credit#150]
Hey there,
It looks like there is something with the repository as I have been trying to clone the files since yesterday.

```
git clone https://github.com/gregcaporaso/tax-credit.git
Cloning into 'tax-credit'...
Username for 'https://github.com': Leo-alves
Password for 'https://Leo-alves@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/gregcaporaso/tax-credit.git/' not found
```

**Comment by nbokulich** [comment]
You are trying to clone a non-existent repo. https://github.com/gregcaporaso/tax-credit does not exist.

https://github.com/caporaso-lab/tax-credit.git is what you should be pointing at.

HOWEVER, this is not the published version of this repo. Clone the latest versions instead:
https://github.com/caporaso-lab/tax-credit-code
https://github.com/caporaso-lab/tax-credit-data
