### ISSUE TITLE
change repo name to reference eval framework and port to biocore

### ISSUE THREAD

**Issue by jairideout** [caporaso-lab/tax-credit#52]
The current repo name `short-read-tax-assignment` made sense when we started this project, but now that we've shifted focus onto the evaluation framework, should we rename it to something that references the framework?

I'm not inspired with any short memorable names right now. @gregcaporaso @nbokulich ideas? Or want to just stick with what we have?

**Comment by nbokulich** [comment]
change to ``tax-credit``

**Comment by nbokulich** [comment]
done
