### ISSUE TITLE
post nick's filtered ITS database

### ISSUE THREAD

**Issue by gregcaporaso** [caporaso-lab/tax-credit#81]
currently available [here](https://dl.dropboxusercontent.com/u/2868868/unite-97-rep-set.tgz) but we need a more stable location before posting

**Comment by nbokulich** [comment]
The old database was replaced by the newest UNITE version.

some filtering does still occur, but we now have a function to automatically do this on any ref db, which we can document as needed.

should we still post our filtered database?

**Comment by nbokulich** [comment]
deleting this issue — think it is outdated.
