### ISSUE TITLE
complete runtime analyses

### ISSUE THREAD

**Issue by gregcaporaso** [caporaso-lab/tax-credit#86]
~~partial output is in `/home/caporaso/analysis/2015.01.06-tax-assignment-runtime/` on bacon~~

**Comment by gregcaporaso** [comment]
Run is completing now. Results are [here](http://nbviewer.ipython.org/github/gregcaporaso/short-read-tax-assignment/blob/master/ipynb/runtime/base.ipynb).

**Comment by nbokulich** [comment]
done
